### ISSUE TITLE
configuration check error

### ISSUE THREAD

**Issue by DSchumacher2104** [rospogrigio/localtuya-homeassistant#64]
I want to use the new integration (2.0) with config flow, so i added only `localtuya:` to configuration.yaml, but when doing a configuration check, it claims:
`Invalid config for [localtuya]: required key not provided @ data['localtuya'][0]['device_id']. Got None
required key not provided @ data['localtuya'][0]['entities']. Got None
required key not provided @ data['localtuya'][0]['friendly_name']. Got None
required key not provided @ data['localtuya'][0]['host']. Got None
required key not provided @ data['localtuya'][0]['local_key']. Got None. (See ?, line ?). `

I think this is not the expected behaviour, right?

**Comment by postlund** [comment]
Can you provide the configuration so we can see what's going on?

**Comment by DSchumacher2104** [comment]
As i wrote, i added nothing, except localtuya:

**Comment by postlund** [comment]
You don't need to add anything to use config flow. If it doesn't show up, try cleaning your cache.

**Comment by DSchumacher2104** [comment]
I removed old version of localtuya and all corresponding entries in configuration.yaml, added v2.0 and restarted HA. After that, i added localtuya: to configuration.yaml and made a config check BEFORE restarting HA again. Then HA throws this error. I didn‘t restart right now. However, i think, the error will disapear After restarting HA. I‘ll report soon.

**Comment by postlund** [comment]
If you are not adding any entries under `localtuya:`, then just omit it from your configuration and you shouldn't have this problem.

**Comment by postlund** [comment]
I don't think this is an actual error as you shouldn't add an empty `localtuya:` row to your configuration, so I will close the issue now. Feel free to open again if you have problems.

**Comment by alexxelax** [comment]
I think I've got a similar issue with my `light` devices in `configuration.yaml`. When I comment lines like `brightness` and `color_temp`, I get no errors:

```
localtuya:
  - host: "192.168.2.45"
    device_id: removed
    local_key: removed
    friendly_name: Bedside Table Tuya 2
    protocol_version: "3.3"
    entities:
      - platform: light
        friendly_name: Bedside Table Tuya 2
        id: 20 
        color_mode: 21 
        # brightness: 22
        # color_temp: 23
        color: 24 
        # brightness_lower: 29 
        # brightness_upper: 255 
        # color_temp_min_kelvin: 1000 
        # color_temp_max_kelvin: 6500 
```
My light appears on the dashboard, without colour wheel though:

![image](https://user-images.githubusercontent.com/25399987/98448103-8b0e8c80-2132-11eb-81e3-4502bbdee895.png)

But when I uncomment all the lines (`brightness`, `color_temp`, etc), I get the following error:

```
Invalid config for [localtuya]: extra keys not allowed @ data['localtuya'][0]['entities'][0]['brightness']. Got 22
extra keys not allowed @ data['localtuya'][0]['entities'][0]['brightness_lower']. Got 29
extra keys not allowed @ data['localtuya'][0]['entities'][0]['brightness_upper']. Got 255
extra keys not allowed @ data['localtuya'][0]['entities'][0]['color']. Got 24
extra keys not allowed @ data['localtuya'][0]['entities'][0]['color_mode']. Got 21
extra keys not allowed @ data['localtuya'][0]['entities'][0]['color_temp']. Got 23
extra keys not allowed @ data['localtuya'][0]['entities'][0]['color_temp_max_kelvin']. Got 6500
extra keys not allowed @ data['localtuya'][0]['entities'][0]['color_temp_min_kelvin']. Got 1000
value is not allowed for dictionary value @ data['localtuya'][0]['entities'][0]['platform']. Got 'light'. (See /config/configuration.yaml, line 53).
```
When I remove `localtuya `from `configuration.yaml` and switch to config flow, I'm able to set values for all those parameters (`brightness`, `color_temp`), and the light appears on the dashboard including colour wheel. 

I downloaded the localtuya master zip today, so I assume I've got the latest version. Home Assistant info:

```
arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.15
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.72
python_version | 3.8.6
supervisor | 2020.11.0
timezone | Africa/Johannesburg
version | 0.117.2
virtualenv | false
```
Am I missing something in my yaml?

As a separate issue: the reason why I'm using yaml instead of config flow is that I have several brands of lights (all are Tuya-based). Some brands have "up to date" firmware version v1.6.1, while others are on v3.3.35. The v1.6.1 lights don't seem to provide any DPS data during the config flow process. The config flow dropdowns are empty, I'm unable to successfully complete the setup since I can't set ID, colour mode, etc. The only way I can connect the v1.6.1 lights is by adding them to `configuration.yaml`.

Just FYI, I get the `invalid config` error on my yaml for both v1.6.1 and v3.3.35 devices.
